const fakeHotel = [
  {
    id: 1,
    place: "Sreemangal",
    title: "Light bright airy stylish apt & safe peaceful stay ",
    roomDetails: "4 guest 2 bedrooms 2 beds 2 bathrooms",
    img: "https://imgur.com/ZRflJbH.jpg",
    wifi: "free wifi",
    cancel: "Cancellation flexibility available",
    rating: "⭐ 4.8(20)",
    price: 35,
    total: 115,
  },
  {
    id: 2,
    place: "Sajek",
    title: "Apartment list in panorama",
    roomDetails: "3 guest 2 bedrooms 2 beds 1 bathrooms",
    img: "https://imgur.com/2BzIwov.jpg",
    wifi: "free wifi",
    cancel: "Cancellation flexibility available",
    rating: "⭐ 4.3(50)",
    price: 25,
    total: 215,
  },
  {
    id: 3,
    place: "Sundarban",
    title: " AR lounge and Pool (r&r + b&b)",
    roomDetails: "2 guest 1 bedrooms 2 beds 2 bathrooms",
    img: "https://imgur.com/l1fVFj5.jpg",
    wifi: "free wifi",
    cancel: "Cancellation flexibility available",
    rating: "⭐ 4.5(70)",
    price: 55,
    total: 155,
  },
  {
    id: 4,
    place: "Sundarban",
    title: "Light bright airy stylish apt & safe peaceful stay ",
    roomDetails: "4 guest 2 bedrooms 2 beds 2 bathrooms",
    img: "https://imgur.com/ZRflJbH.jpg",
    wifi: "free wifi",
    cancel: "Cancellation flexibility available",
    rating: "⭐ 4.8(20)",
    price: 35,
    total: 115,
  },
  {
    id: 5,
    place: "Sreemangal",
    title: "Apartment list in panorama",
    roomDetails: "3 guest 2 bedrooms 2 beds 1 bathrooms",
    img: "https://imgur.com/2BzIwov.jpg",
    wifi: "free wifi",
    cancel: "Cancellation flexibility available",
    rating: "⭐ 4.3(50)",
    price: 25,
    total: 215,
  },
  {
    id: 6,
    place: "Sajek",
    title: " AR lounge and Pool (r&r + b&b)",
    roomDetails: "2 guest 1 bedrooms 2 beds 2 bathrooms",
    img: "https://imgur.com/l1fVFj5.jpg",
    wifi: "free wifi",
    cancel: "Cancellation flexibility available",
    rating: "⭐ 4.5(70)",
    price: 55,
    total: 155,
  },
  {
    id: 7,
    place: "Sajek",
    title: " AR lounge and Pool (r&r + b&b)",
    roomDetails: "4 guest 2 bedrooms 2 beds 2 bathrooms",
    img: "https://imgur.com/ZRflJbH.jpg",
    wifi: "free wifi",
    cancel: "Cancellation flexibility available",
    rating: "⭐ 4.8(20)",
    price: 35,
    total: 115,
  },
  {
    id: 8,
    place: "Sundarban",
    title: "Apartment list in panorama",
    roomDetails: "3 guest 2 bedrooms 2 beds 1 bathrooms",
    img: "https://imgur.com/2BzIwov.jpg",
    wifi: "free wifi",
    cancel: "Cancellation flexibility available",
    rating: "⭐ 4.3(50)",
    price: 25,
    total: 215,
  },
  {
    id: 9,
    place: "Sreemangal",
    title: " AR lounge and Pool (r&r + b&b)",
    roomDetails: "2 guest 1 bedrooms 2 beds 2 bathrooms",
    img: "https://imgur.com/l1fVFj5.jpg",
    wifi: "free wifi",
    cancel: "Cancellation flexibility available",
    rating: "⭐ 4.5(70)",
    price: 55,
    total: 155,
  },
];
export default fakeHotel;
